[package]
name = "mcl-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.17"
bitflags = "2.10.0"
url = { version = "2.5", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
bytes = "1.11.0"
serde = { version = "1", features = ["derive", "rc"] }
serde_with = "3.12"
zip = "6.0.0"
sha1_smol = { version = "1.0.1", features = ["serde"] }

[dev-dependencies]
serde_json = "1"
tokio = { version = "1.8", features = ["full"] }
reqwest = "0.12.24"
futures = "0.3.31"
